version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pomer
      - POSTGRES_DB=jwt_database
    volumes:
      - ./pgdata:/var/lib/postgres/data
  backend: 
    image: jwt_server
    container_name: backend
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "3001:3001"
  frontend:
    image: frontend_jwt
    container_name: front
    depends_on:
      - db
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
